CREATE USER customer1 IDENTIFIED BY password;
CREATE USER driver2 IDENTIFIED BY password;
CREATE USER agent3 IDENTIFIED BY password;
CREATE USER manager4 IDENTIFIED BY password;

--GRANT CREATE SESSION TO customer1, driver2, agent3, manager4;

GRANT CREATE SESSION TO customer1 WITH ADMIN OPTION;
GRANT CREATE SESSION TO driver2 WITH ADMIN OPTION;
GRANT CREATE SESSION TO agent3 WITH ADMIN OPTION;
GRANT CREATE SESSION TO manager4 WITH ADMIN OPTION;

GRANT SELECT, INSERT, UPDATE ON system.Customer TO customer1;
GRANT SELECT, INSERT, UPDATE ON system.Customer TO agent3;
GRANT SELECT, INSERT, UPDATE ON system.Customer TO manager4;

GRANT SELECT, INSERT, UPDATE ON Driver TO driver2;
GRANT SELECT, INSERT, UPDATE ON Driver TO agent3;
GRANT SELECT, INSERT, UPDATE ON Driver TO manager4;

GRANT SELECT, INSERT, UPDATE ON Agent TO agent3;
GRANT SELECT, INSERT, UPDATE ON Agent TO manager4;

GRANT SELECT, INSERT, UPDATE ON Manager TO manager4;

GRANT SELECT, INSERT, UPDATE ON Booking TO customer1;
GRANT SELECT, INSERT, UPDATE ON Booking TO driver2;
GRANT SELECT, INSERT, UPDATE ON Booking TO agent3;
GRANT SELECT, INSERT, UPDATE ON Booking TO manager4;

GRANT SELECT, INSERT, UPDATE ON FEEDBACK TO customer1;
GRANT SELECT, INSERT, UPDATE ON FEEDBACK TO driver2;
GRANT SELECT, INSERT, UPDATE ON FEEDBACK TO agent3;
GRANT SELECT, INSERT, UPDATE ON FEEDBACK TO manager4;


